chore: use python 3.11 for docker and fix versions
with the python3.10 there was a weird error occuring on startup:
```
init <class 'backend.database.models.offers.Offer'>
ERROR:    Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 654, in startup
    await handler()
  File "/backend/backend/main.py", line 23, in startup
    await init_db()
  File "/backend/backend/database/connection.py", line 39, in init
    await init_beanie(database=client.AR, document_models=[d])
  File "/usr/local/lib/python3.10/site-packages/beanie/odm/utils/init.py", line 735, in init_beanie
    await Initializer(
  File "/usr/local/lib/python3.10/site-packages/beanie/odm/utils/init.py", line 113, in __init__
    self.fill_docs_registry()
  File "/usr/local/lib/python3.10/site-packages/beanie/odm/utils/init.py", line 129, in fill_docs_registry
    if inspect.isclass(obj) and issubclass(obj, BaseModel):
  File "/usr/local/lib/python3.10/abc.py", line 123, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
TypeError: issubclass() arg 1 must be a class
```

This only happened when initializing the Offer model. I was too lazy to
find the exact error behind this and instead opted for upgrading to 3.11
as there was no error with that version...